version: "3.7"

services:
  # Server MYSQL
  mysql-dev:
    container_name: tgs_mysql_dev
    image: mysql:5.7
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - tgs

  # Mysql Test
  mysql-test:
    container_name: tgs_mysql_test
    image: mysql:5.7
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    env_file:
      - .env.testing
    ports:
      - 3307:3306
    volumes:
      - mysql_test_data:/var/lib/mysql
    networks:
      - tgs

  # Redis Server
  redis-dev:
    container_name: tgs_redis_dev
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    networks:
      - tgs

volumes:
  mysql_data:
  mysql_test_data:

networks:
  tgs:
    driver: bridge
